version: '3'

services:
  front:
    build: ./front
    volumes:
      - ./front:/app
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    environment:
      BASE_URL: 'http://api.stg.image-q.com'
    command: sh -c "yarn dev"
  api:
    build: ./api
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    ports:
      - '5000:80'
    tty: true
    stdin_open: true
    command: sh -c "rm -f /app/tmp/pids/server.pid && ./bin/setup && rails s -b 0.0.0.0 -p 80"
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'

volumes:
  bundle:
  mysql_data:
